from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719b2dc37136'
down_revision = 'fa3a4229a256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_code', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint('uq_recovery_code', ['recovery_code'])  # Nombre de la restricción

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_recovery_code', type_='unique')  # Nombre de la restricción
        batch_op.drop_column('recovery_code')

    # ### end Alembic commands ###
