"""add recovery_codes_json column

Revision ID: 950f9bcff86c
Revises: 719b2dc37136
Create Date: 2025-08-16 10:33:31.062597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950f9bcff86c'
down_revision = '719b2dc37136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_codes_json', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_recovery_code'), type_='unique')
        batch_op.drop_column('recovery_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_code', sa.VARCHAR(length=32), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_recovery_code'), ['recovery_code'])
        batch_op.drop_column('recovery_codes_json')

    # ### end Alembic commands ###
